### ISSUE TITLE
Problem in example with "autoform"?

### ISSUE THREAD

**Issue by thearabbit** [usefulio/wizard#2]
Thanks for your example, but `next` and `insert` don't work.
It work, when I click the `next` two time (no double click).
In other hand should be have `previous` btn.
Excuse me, you can example with `bootstrap 3`.

**Comment by thearabbit** [comment]
Excuse me, the `insert` work fine.

**Comment by ianserlin** [comment]
I actually never use autoform, so I'm going to leave this to the community then if they want to keep up to date with autoform compatibility.

**Comment by thearabbit** [comment]
Thanks, good job.

**Comment by olumytee** [comment]
Hello @thearabbit , did you find a way to make previous button work with autoform ?

**Comment by thearabbit** [comment]
Now you can try [This](https://github.com/thearabbit/autoform-wizard-example)
