### ISSUE TITLE
moveToIndex in template.onCreated throws error...

### ISSUE THREAD

**Issue by DanielDornhardt** [usefulio/wizard#3]
...because setClasses gets called which tries to use the instances' $ - property to add the classes. But the $ - property doesn't exist yet.

**Comment by ianserlin** [comment]
In `onCreated` it might be more meaningful to simply use `this.currentIndex.set(desiredIndex)`, however I don't think it should bomb your app/template if you do use `moveToIndex` in `onCreated`.

So now, if the view isn't rendered yet, `moveToIndex` simply calls `currentIndex.set` for you.

Updated and published as version 0.0.4.

Thanks!

**Comment by DanielDornhardt** [comment]
Thank you! I posted the issue because it was documented as "should work": "In an onCreated/onRendered/onDestroyed, use this.moveToIndex(targetIndex).".

So thank you for fixing this and all the best! :)
